kind: pipeline
type: docker
name: default
node:
  region: cn
steps:
  - name: generate
    pull: if-not-exists
    image: ccr.ccs.tencentyun.com/xiaoqidun/build
    commands:
      - build -f build.sh -i ihash.go -o release/ihash
  - name: build
    pull: if-not-exists
    image: ccr.ccs.tencentyun.com/xiaoqidun/goenv
    commands:
      - ./build.sh
  - name: upload
    pull: if-not-exists
    image: ccr.ccs.tencentyun.com/xiaoqidun/gocos
    settings:
      secret_id:
        from_secret: cos_secret_id
      secret_key:
        from_secret: cos_secret_key
      bucket_url:
        from_secret: cos_bucket_url
      source: release/
      target: product/ihash
      strip_prefix: release/